name: Build and Release Go Project
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Build for Linux-arm64
        run: |
          GOARCH=arm64 GOOS=linux go build -o bin/pmls-arm64
      - name: Build for Linux-amd64
        run: |
          GOARCH=amd64 GOOS=linux go build -o bin/pmls-amd64
      - name: Release builds
        uses: actions/gitea-release-action@v1
        with:
          files: |-
            bin/**
